version: "3.3"
services:
  mysql-server-user:
    command: --default-authentication-plugin=mysql_native_password
    image: "mysql"
    volumes:
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    restart: on-failure
    environment:
      - MYSQL_ROOT_HOST=172.17.0.1
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=user
    ports:
      - "3307:3306"
    restart: always
  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: always
